[package]
name = "zed_ton"
version = "0.0.1"
edition = "2021"
publish = false
license = "MIT"

[lib]
path = "src/ton.rs"
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
zed_extension_api = "0.7.0"
